include: package:dart_flutter_team_lints/analysis_options.yaml

analyzer:
  language:
    strict-raw-types: true
  exclude:
    - test/test_files/**

linter:
  rules:
    - prefer_final_in_for_each
    - prefer_final_locals
