name: dart_syntax_highlight
publish_to: none
environment:
  sdk: ^3.2.0

dev_dependencies:
  collection: ^1.19.0
  dart_flutter_team_lints: ^3.2.1
  path: ^1.9.0
  string_scanner: ^1.4.0
  test: ^1.25.8
