name: dart_syntax_highlight
publish_to: none
environment:
  sdk: ^3.2.0

dev_dependencies:
  collection: ^1.18.0
  dart_flutter_team_lints: ^2.1.1
  path: ^1.9.0
  string_scanner: ^1.2.0
  test: ^1.25.2
